language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly

sudo: required

git:
  depth: 9999

notifications:
  email: false

branches:
  only:
    - master

after_success:
  - julia -e 'cd(Pkg.dir("LDLFactorizations")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
